language: android

android:
  components:
    - tools
    - platform-tools
    - tools # travis build issue
    - build-tools-27.0.3
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - android-27
    - sys-img-armeabi-v7a-android-27

jdk:
  - oraclejdk8

before_script:
  - echo no | android create avd --force --name test --target android-27 --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &amp;

script:
  - ./gradlew check -PdisablePreDex --continue --stacktrace
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &amp;
  - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace

notifications:
  email: false

sudo: false
install: skip

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
