language: android

android:
  components:
    - tools
    - platform-tools
    - tools # travis build issue
    - build-tools-27.0.3
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - android-24
    - sys-img-armeabi-v7a-android-24
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jdk:
  - oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-27"

before_script:
  - echo no | android create avd --force --name test --target android-24 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &

script:
  - ./gradlew check -PdisablePreDex --continue --stacktrace
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace

notifications:
  email: false

sudo: false
install: skip

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
