language: android

android:
  components:
    - tools
    - platform-tools
    - tools # travis build issue
    - extra-android-m2repository
    - android-27

jdk:
  - oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-27 ANDROID_ABI=google_apis/armeabi-v7a

before_script:
  - echo no | android create avd --force --name test --target android-27 --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &amp;

script:
  - ./gradlew check -PdisablePreDex --continue --stacktrace
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &amp;
  - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace

notifications:
  email: false

sudo: false

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
